name: Deploy to EC2

on:
  push:
    branches:
      - main # Triggers on push to the main branch

jobs:
  build-and-deploy:
    runs-on: self-hosted # Use the self-hosted runner

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Build Docker image and deploy
        run: |
          # Navigate to the app directory, or clone the latest version if needed
          cd ~/bot844/twitchbot || git clone https://github.com/nick8440/twitchbot.git ~/bot844/twitchbot && cd ~/bot844/twitchbot

          # Pull the latest code
          git pull origin main

          # Build the Docker image locally on EC2
          docker build -t bot844-image .

          # Stop and remove any existing container
          docker stop bot844 || true
          docker rm bot844 || true

          # Run the new container with the updated image
          docker run -d --name bot844 -p 8000:8000 --env-file ../.env bot844-image:latest
